---
- name: Install the nginx packages
  apt: name={{ item }} state=present
  with_items: "{{ nginx_ubuntu_pkg }}"
  environment: "{{ nginx_env }}"
  when: ansible_os_family == "Debian"
  tags: [packages,nginx]
