---
- name: install artifact
  copy: src="../target/{{app_name}}.jar" dest="/opt/sr-{{app_name}}/jar/sr-{{app_name}}.jar" force=yes
- name: restart service
  service: name=sr-{{app_name}} state=restarted