---
 - hosts: webhook-recorder
   sudo: yes
   roles:
   - role: ansible-java8-oracle
   - role: revo-app
     xmx: 256m
     xms: 128m
     jmx_port: 22345
     debug_port: 7666
     tags: install
     app_name: webhook-recorder

   - role: deploy
     tags: deploy
     app_name: webhook-recorder

   - role: jdauphant.nginx
     nginx_sites:
       webhook-recorder:
         - listen 8080
         - server_name recorder.sarbacane.com
         - root "/var/www/webhook"
         - location /record {
             proxy_pass http://localhost:8081/webhook;
           }
         - location / { try_files $uri $uri/ /index.html; }
     tags: nginx
