---
 - hosts: webhook-recorder
   sudo: yes
   roles:
   - role: revo-app
     xmx: 256m
     xms: 128m
     jmx_port: 22345
     debug_port: 7666
     tags: install
     app_name: webhook-recorder

   - role: deploy
     tags: deploy
     app_name: webhook-recorder

   - role: jdauphant.nginx
     nginx_sites:
       webhook-recorder:
         - listen 80
         - server_name recorder.sarbacane.com
         - location / {
         - proxy_pass http://localhost:8080/
         - "}"
     tags: nginx
