- src: git+ssh://git@git.sarbacane.com/sarbacane-software/ansible-role-revo-app.git
  version: master
  path: roles
  name: revo-app
- name: jdauphant.nginx
- name: ansible-java8-oracle
  src: https://github.com/malk/ansible-java8-oracle.git